# Generated by Django 5.2.7 on 2025-10-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfid_receiver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfidlog",
            name="name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
